baseURL = "http://hicoldcat.com/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "李留白，探索发现频道"
theme = "DoIt"
summaryLength = 400.0
googleAnalytics = ""
enableRobotsTXT = true

[params]
version = "0.2.X"

  [params.page]

    [params.page.toc]
    enable = true
    keepStatic = true

    [params.page.code]
    copy = true
    maxShownLines = 100.0

    [params.page.share]
    enable = true
    Weibo = true

    [params.page.comment]
    enable = false

      [params.page.comment.disqus]
      enable = false
      shortname = "li-liu-bai"

  [params.header]

    [params.header.title]
    logo = "/images/logo.svg"
    name = "李留白"
    pre = ""
    post = ""
    typeit = true

  [params.home]

    [params.home.profile]
    enable = true
    avatarURL = "/images/avatar.jpg"
    title = "李留白"
    subtitle = "Web3布道师。全栈开发工程师，专注Web3(区块链、元宇宙、XR、DAO、NFT)......"
    typeit = true
    social = true
    disclaimer = ""

  [params.section]
  paginate = 20.0
  dateFormat = "01-02"
  rss = 20.0

    [params.section.recentlyUpdated]
    enable = true
    rss = true
    days = 30.0
    maxCount = 20.0

  [params.social]

    [params.social.GitHub]
    weight = 0.0
    id = "hicoldcat"
    prefix = "https://github.com/"
    title = "GitHub"

    [params.social.Zhihu]
    weight = 0.0
    id = "hicoldcat"
    prefix = "https://www.zhihu.com/people/"
    title = "李留白"

    [params.social.Email]
    weight = 0.0
    id = "hicoldcat@foxmail.com"
    title = "李留白"

  [params.footer]
  enable = true
  custom = ""
  hugo = false
  copyright = true
  author = true
  since = 2022.4
  icp = "<a href='https://beian.miit.gov.cn/'>浙ICP备2022012706号-1</a>"
  license = ""

[menu]

  [[menu.main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "文章"
  url = "/posts/"
  title = ""
  weight = 1.0

  [[menu.main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 3.0

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  noClasses = false

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.renderer]
    unsafe = true